CREATE TABLE `amplopayPixPayments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderCode` varchar(64) NOT NULL,
	`identifier` varchar(96) NOT NULL,
	`transactionId` varchar(128),
	`status` enum('PENDING','PAID','FAILED','REJECTED','CANCELED','REFUNDED','CHARGED_BACK') NOT NULL DEFAULT 'PENDING',
	`amountCents` int NOT NULL,
	`buyerName` varchar(255) NOT NULL,
	`buyerEmail` varchar(320) NOT NULL,
	`buyerDocument` varchar(64) NOT NULL,
	`cinema` json NOT NULL,
	`session` json NOT NULL,
	`seats` json NOT NULL,
	`pixCode` text,
	`pixImageUrl` text,
	`webhookToken` varchar(512),
	`lastWebhookEvent` varchar(64),
	`webhookProcessedAt` timestamp,
	`paidAt` timestamp,
	`providerPayload` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `amplopayPixPayments_id` PRIMARY KEY(`id`),
	CONSTRAINT `amplopayPixPayments_orderCode_unique` UNIQUE(`orderCode`),
	CONSTRAINT `amplopayPixPayments_identifier_unique` UNIQUE(`identifier`),
	CONSTRAINT `amplopayPixPayments_transactionId_unique` UNIQUE(`transactionId`)
);
